// This file is auto-generated by `npm run sync:linktree`.

export const LINKTREE_TIMELINE_META = {
  "schemaVersion": 1,
  "generatedAt": "2026-03-08T11:38:40.923Z",
  "sourceUrl": "https://linktr.ee/a_e.s_",
  "sourceUpdatedAt": "2026-02-16T17:38:55.000Z",
  "itemCount": 24
} as const;

export const LINKTREE_TIMELINE_ENTRIES = [
  {
    "title": "Scraps: Dark Days, Symptoms of An Ill Mind, & No Context Demos Tapes (2023-2024)",
    "aliases": [
      "Scraps 2023-2024"
    ],
    "type": "CLASSIC",
    "sourcePosition": 2,
    "urls": [
      "https://untitled.stream/invite/sUL08iLtaVYP3UbF2ehDg"
    ],
    "sourceGroup": "In 2023 I Made",
    "yearLabel": "2023-2024",
    "sortYear": 2024
  },
  {
    "title": "Practicing Kriya",
    "aliases": [],
    "type": "CLASSIC",
    "sourcePosition": 0,
    "urls": [
      "https://drive.google.com/file/d/1TcERCTJS1opeyJJ3A5SSFHQBvF7LLBc6/view?usp=drivesdk"
    ],
    "sourceGroup": null,
    "yearLabel": null,
    "sortYear": null
  },
  {
    "title": "End! (First Ten Pages Of A Screenplay for HBO)",
    "aliases": [],
    "type": "EXTENSION",
    "sourcePosition": 3,
    "urls": [],
    "sourceGroup": "In 2020 I Made",
    "yearLabel": "2020",
    "sortYear": 2020
  },
  {
    "title": "Cocoa (First Page Of My Screenplay!)",
    "aliases": [],
    "type": "EXTENSION",
    "sourcePosition": 1,
    "urls": [],
    "sourceGroup": "In 2020 I Made",
    "yearLabel": "2020",
    "sortYear": 2020
  },
  {
    "title": "The Everyday Life Video",
    "aliases": [],
    "type": "YOUTUBE_VIDEO",
    "sourcePosition": 2,
    "urls": [
      "https://youtu.be/KWDgWpSDlrM?si=-3TuP0xU0t5egiZA"
    ],
    "sourceGroup": "In 2019 I Made",
    "yearLabel": "2019",
    "sortYear": 2019
  },
  {
    "title": "Volume 4 - Angel Suero’s Top 50 Most Played Songs",
    "aliases": [
      "Volume 4",
      "Volume 4 Smart Link",
      "Volume 4 - Spotify",
      "Volume 4 - SoundCloud",
      "Volume 4 - YouTube Music"
    ],
    "type": "CLASSIC",
    "sourcePosition": 3,
    "urls": [
      "https://sdz.sh/yFOERE"
    ],
    "sourceGroup": "In 2017 - 2018 I Made",
    "yearLabel": "2017-2018",
    "sortYear": 2018
  },
  {
    "title": "Angel Suero’s Top 100 Most Played Songs",
    "aliases": [
      "Volume 1",
      "Volume 1 Linktree",
      "Volume 1 - Spotify",
      "Volume 1 - SoundCloud",
      "Volume 1 - YouTube Music"
    ],
    "type": "CLASSIC",
    "sourcePosition": 1,
    "urls": [
      "https://linktr.ee/a_e.s_playlist"
    ],
    "sourceGroup": "In 2015 - 2016 I Made",
    "yearLabel": "2015-2016",
    "sortYear": 2016
  },
  {
    "title": "My Personal Statement",
    "aliases": [],
    "type": "EXTENSION",
    "sourcePosition": 1,
    "urls": [],
    "sourceGroup": "In 2019 I Made",
    "yearLabel": "2019",
    "sortYear": 2019
  },
  {
    "title": "This Essay I Wrote On Happiness",
    "aliases": [],
    "type": "EXTENSION",
    "sourcePosition": 0,
    "urls": [],
    "sourceGroup": "In 2019 I Made",
    "yearLabel": "2019",
    "sortYear": 2019
  },
  {
    "title": "Writing - Vonnegut",
    "aliases": [
      "Writing - Vonnegut"
    ],
    "type": "EXTENSION",
    "sourcePosition": 1,
    "urls": [],
    "sourceGroup": "In 2017 - 2018 I Made",
    "yearLabel": "2017-2018",
    "sortYear": 2018
  },
  {
    "title": "My First Beat Tape",
    "aliases": [],
    "type": "CLASSIC",
    "sourcePosition": 1,
    "urls": [
      "https://untitled.stream/library/project/W9oQWS6klQAAftkyx28QL"
    ],
    "sourceGroup": null,
    "yearLabel": null,
    "sortYear": null
  },
  {
    "title": "Scraps: The Death Of My Feminine Demos (2022)",
    "aliases": [],
    "type": "CLASSIC",
    "sourcePosition": 1,
    "urls": [],
    "sourceGroup": "In 2022 I Made",
    "yearLabel": "2022",
    "sortYear": 2022
  },
  {
    "title": "A Magazine Publication - The Art of Survival",
    "aliases": [
      "The Art of Survival"
    ],
    "type": "CLASSIC",
    "sourcePosition": 2,
    "urls": [
      "https://jstrieb.github.io/link-lock/#eyJ2IjoiMC4wLjEiLCJlIjoiNzkzazQ2c0hQdmlxVlRDNGZmbW1KOU5nY1JWMmtUNVRCV250QXhJcUJEZ080ejduL0dsT2dobVNhNWU0MURvUUdFL1BhbHZjZWZmYmZiY0xwenI0RWY2SmJSYXdoa1NEUVh4K2RQRytOR3g3NTY1UjJQTzVVelpCIiwicyI6Imx4S3czNXJUMmt2Y0ZETFVEb3Boa3c9PSIsImkiOiJrY3VDKzdCTjV6eHdIcWd2In0="
    ],
    "sourceGroup": "In 2022 I Made",
    "yearLabel": "2022",
    "sortYear": 2022
  },
  {
    "title": "Queries (The Beat Tape): Family... Love?",
    "aliases": [
      "Queries Beat Tape"
    ],
    "type": "CLASSIC",
    "sourcePosition": 0,
    "urls": [
      "https://untitled.stream/library/project/yJu7cTKC0F3qvrRqs2EzA"
    ],
    "sourceGroup": "In 2020 I Made",
    "yearLabel": "2020",
    "sortYear": 2020
  },
  {
    "title": "Angel Suero’s Top 50 Most Played Songs",
    "aliases": [
      "Volume 2",
      "Volume 2 Linktree",
      "Volume 2 - Spotify",
      "Volume 2 - SoundCloud",
      "Volume 2 - YouTube Music"
    ],
    "type": "CLASSIC",
    "sourcePosition": 2,
    "urls": [
      "https://linktr.ee/a_e.s_volume2"
    ],
    "sourceGroup": "In 2015 - 2016 I Made",
    "yearLabel": "2015-2016",
    "sortYear": 2016
  },
  {
    "title": "SCRAPS AFTER HEARTBREAKS MUSICVIDEO",
    "aliases": [],
    "type": "YOUTUBE_VIDEO",
    "sourcePosition": 0,
    "urls": [
      "https://youtu.be/ErIkkP7lmEw?si=AiU5QA_um1BIWmpv"
    ],
    "sourceGroup": "In 2023 I Made",
    "yearLabel": "2023",
    "sortYear": 2023
  },
  {
    "title": "Angel Suero’s Top 50 Most Played Songs",
    "aliases": [
      "Volume 3",
      "Volume 3 Smart Link",
      "Volume 3 - Spotify",
      "Volume 3 - SoundCloud",
      "Volume 3 - YouTube Music"
    ],
    "type": "CLASSIC",
    "sourcePosition": 0,
    "urls": [
      "https://sdz.sh/FDoCqk"
    ],
    "sourceGroup": "In 2015 - 2016 I Made",
    "yearLabel": "2015-2016",
    "sortYear": 2016
  },
  {
    "title": "Writing - Life In IB",
    "aliases": [
      "Writing - Life In IB"
    ],
    "type": "EXTENSION",
    "sourcePosition": 0,
    "urls": [],
    "sourceGroup": "In 2017 - 2018 I Made",
    "yearLabel": "2017-2018",
    "sortYear": 2018
  },
  {
    "title": "Gaming With Angel (DBSZ)",
    "aliases": [],
    "type": "YOUTUBE_VIDEO",
    "sourcePosition": 0,
    "urls": [
      "https://youtu.be/YWZN2og3Y48"
    ],
    "sourceGroup": null,
    "yearLabel": null,
    "sortYear": null
  },
  {
    "title": "'Gram",
    "aliases": [
      "Instagram"
    ],
    "type": "INSTAGRAM_PROFILE",
    "sourcePosition": 8,
    "urls": [
      "https://www.instagram.com/a_e.s_"
    ],
    "sourceGroup": null,
    "yearLabel": null,
    "sortYear": null
  },
  {
    "title": "The Every Day Soundscape",
    "aliases": [],
    "type": "CLASSIC",
    "sourcePosition": 3,
    "urls": [
      "https://untitled.stream/library/track/tbolNlQAX1cXSZr3bLWeh"
    ],
    "sourceGroup": "In 2019 I Made",
    "yearLabel": "2019",
    "sortYear": 2019
  },
  {
    "title": "Resources For Humans",
    "aliases": [],
    "type": "CLASSIC",
    "sourcePosition": 20,
    "urls": [
      "https://linktr.ee/resourcesonlyforhumans"
    ],
    "sourceGroup": null,
    "yearLabel": null,
    "sortYear": null
  },
  {
    "title": "Angel’s Evolving AI Pledge",
    "aliases": [
      "Angel's Evolving AI Pledge",
      "AI Pledge"
    ],
    "type": "EXTENSION",
    "sourcePosition": 21,
    "urls": [],
    "sourceGroup": null,
    "yearLabel": null,
    "sortYear": null
  },
  {
    "title": "Legal Notice, Usage, & Licensing Terms",
    "aliases": [],
    "type": "EXTENSION",
    "sourcePosition": 22,
    "urls": [],
    "sourceGroup": null,
    "yearLabel": null,
    "sortYear": null
  }
] as const;
